---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates for (CentOS)
    tags: CentOS
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS" 

  - name: install updates for (Ubuntu)
    tags: Ubuntu
    apt: 
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu" 

- hosts: all 
  become: true
  roles: 
    - base


- hosts: bastion
  become: true
  roles:
    - web_servers


- hosts: db_servers
  become: true
  roles:
    - db_servers


- hosts: workstations
  become: true 
  roles: 
    - workstations


