---

- hosts: all
  become: true
  pre_tasks:


  - name: install updates for (CentOS)
    tags: CentOS
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS" 

  - name: install updates for (Ubuntu)
    tags: Ubuntu
    apt: 
      update_cache: yes
    when: ansible_distribution == "Ubuntu" 

- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 and libapache2-mod-php packages
    tags: apache apache2 libapache2-mod-php
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package for (CentOS)
    tags: mariadb CentOS
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install mariadb package for (Ubuntu)
    tags: Ubuntu mariadb
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"
    