  - name: install mariadb package for (CentOS)
    tags: mariadb CentOS
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install mariadb package for (Ubuntu)
    tags: Ubuntu mariadb
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"